### ISSUE TITLE
AccountResp.RAMQuota cannot be parsed, on the test network, when the ram is too large

### ISSUE THREAD

**Issue by yukunyi** [eoscanada/eos-go#103]
the 'eos.GetAccount' method error : 

> Unmarshal: json: cannot unmarshal string into Go struct field AccountResp.ram_quota of type int64

I got json from cli is  

> "ram_quota": "5186668695"

In json field 'ram_quota' type is string. so convert to int64 fail.

**Comment by billettc** [comment]
fix: https://github.com/eoscanada/eos-go/commit/299c8165936da2fe22504739394fcc45dbfc3c18
