### ISSUE TITLE
go.uber.org/zap get 不下来

### ISSUE THREAD

**Issue by liyue201** [eoscanada/eos-go#106]
万恶的防火墙

**Comment by anthonyzzy** [comment]
this user couldn't get `go.uber.org/zap` and his comment is "The damn firewall."

**Comment by maoueh** [comment]
[go.uber.org.zip](https://github.com/eoscanada/eos-go/files/2741383/go.uber.org.zip)

Package needed to compile eos-go.

1. Download package to local computer (assuming `/tmp/go.uber.org.zip`)
2. `cd $GOPATH/src`
3. `unzip /tmp/go.uber.org.zip`

Enjoy

**Comment by liyue201** [comment]
thx
