### ISSUE TITLE
can not unmarshal string into int64 on get action request for param account_seq

### ISSUE THREAD

**Issue by KePeng1019** [eoscanada/eos-go#107]
for some account have many action history, the get action call failed because json form value can not represent int number more then int32 and turn it into string, so unmarshal failed today. current the global_seq param is too large, please fix it.

**Comment by KePeng1019** [comment]
because current eos global_seq is too large to present by json number, so the return value is string, please fix it, the lib get action do not work now.

**Comment by KePeng1019** [comment]
> There are many places that have this problem, I temporarily modified the code to use first.

so this problem is fixed now?

**Comment by yukunyi** [comment]
@KePeng1019 
I just modified it temporarily in my local area. I also mentioned a similar error before, just the field of another object.

**Comment by billettc** [comment]
This should be fixed by commit
https://github.com/eoscanada/eos-go/commit/0ea2f0068762d58942ba290014efa38ad1429f85

**Comment by abourget** [comment]
We also went over the code to modify those who could fail in the future.

Please note also that `JSONInt64` is deprecated, use `Int64` instead (it's type aliased right now, so it'll work.. but just so you know :)

**Comment by abourget** [comment]
Actually, `global_sequence` and  `recv_sequence` (along with a few others) are actually UNSIGNED int64. I'll roll out changes right now, hopefully we're done with this.
