### ISSUE TITLE
uint16 is not enough for TransactionHeader.RefBlockNum

### ISSUE THREAD

**Issue by Tokyliu** [eoscanada/eos-go#109]

**Comment by Tokyliu** [comment]
> Check nodeos' code. It's indeed a uint16 :-) nothing would work if that wasn't right

TransactionHeader.RefBlockNum is refer to the value of block num, and the max block num of eos is more than 65535, so i think uint16 and is not enough.

**Comment by Tokyliu** [comment]
another question: API.GetBlockByNum($blockNum) call get an error(Unmarshal: get id: unpacking Transaction, uint64 required [8] bytes, remaining [0]) occasionally.

**Comment by Tokyliu** [comment]
i find the same issue, #27 , thanks you! @abourget

**Comment by maoueh** [comment]
@Tokyliu In my email notifications, I see you wrote: 

> another question: API.GetBlockByNum($blockNum) call get an error(Unmarshal: get id: unpacking Transaction, uint64 required [8] bytes, remaining [0]) occasionally.

I don't find the comment anymore. Do you by chance have the `blockNum` that caused the issued?

**Comment by Tokyliu** [comment]
sorry, @maoueh . It was not a real issue, just found a mistake i made. So i delete it, and you received the email notification, just ignore it  @maoueh, thanks.
