### ISSUE TITLE
ActionTrace's Receipt can't Unmarshal

### ISSUE THREAD

**Issue by jackami** [eoscanada/eos-go#114]
When I call GetTansaction API, Receipt and ActionTrace‘s Receipt cannot be parsed in the returned result。
TKS

**Comment by maoueh** [comment]
Please provide some source code so that we can help fix the issue. Please also provide any further information required like API node used, actual transaction id, etc.

**Comment by jackami** [comment]
![image](https://user-images.githubusercontent.com/5304811/53061440-a1a52800-34f8-11e9-9846-cd8f6911309b.png)

```
func TestGetTransactionParse(t *testing.T) {
	client := eos.New("https://nodes.get-scatter.com")
	resp, err := client.GetTransaction("a96cf59c7dbd7279bc3905c631d0655be5f3ef9ad04d00b2b2a769278aaae28c")
	if err != nil {
		return
	}
	for _, t := range resp.Traces {
		fmt.Println(t.Receipt.ActionDigest)
	}
}
```

I use the Goland IDE to debug the code, and the Receipt information can't be displayed normally, but it can be output by field. 😓

**Comment by maoueh** [comment]
Did you resolve the problem?
