### ISSUE TITLE
sometimes the api occur this problem. push transaction: Internal Service Error: Invalid Reference Block.. 

### ISSUE THREAD

**Issue by inkbx** [eoscanada/eos-go#134]
what's this mean and how to fix ?

**Comment by abourget** [comment]
Maybe you didn't get a reference block from the same chain.. or you're talking to an out-of-sync node. The transaction must have sourced its reference block from a recent block on the same chain you're going to push it.

I'll close this as this is more general purpose EOSIO support, which can be directed to either Stack Exchange, or Telegram channels.

thanks!
