### ISSUE TITLE
About transaction packed document

### ISSUE THREAD

**Issue by yankunsam** [eoscanada/eos-go#14]
I am confused about the transaction packed. So can you supply the detail about packing a transaction?
"eos" did not pack for a transaction.  Thanks.

**Comment by abourget** [comment]
@yankunsam I think we had a chat on Telegram, right ? Did you solve your issue?

binary.go has most of the packing/unpacking.. but all the JSON to internal representation has its own quirks.. which isn't "packing" per se..

Lots of fun.

Some aren't aware of the API endpoints here: `/v1/chain/abi_to_json` and `/v1/chain/json_to_abi`.. that can be helpful to do packing and unpacking when you don't have much tools around.

Tell me if I can close this.

**Comment by yankunsam** [comment]
Sorry maybe we don't have a chat about this topic. I did not solve my issue.  I can not understand so many fc::pack. You mean that it is useful by "/v1/chain/abi_to_json" and "/v1/chain/json_to_abi" to pack a transaction?

**Comment by maoueh** [comment]
@yankunsam Can you add more details about what you would like to know. A bullet list would help me getting you the information you are seeking.

**Comment by yankunsam** [comment]
@maoueh  Thanks for your reply. Actually, I think that eos should supply the transaction packed HTTP API. Like "cleos" they have. The detail is the implementation of "packs()" in eos C++. I know it just for json to binary.

**Comment by maoueh** [comment]
I'm not sure I fully get what you mean. Are you suggesting `eos` itself should be changed to supply an API to fetch the packed transaction?

I'm not sure I understand the link between your comment and this library (`eos-go`).

**Comment by maoueh** [comment]
Closing since highly unrelated to the library. Feel free to continue the discussion here so we can route you to the right communication channel.
