### ISSUE TITLE
parse blocks.log get a panic

### ISSUE THREAD

**Issue by sdl9i2** [eoscanada/eos-go#152]
prev decoding signed block: packed transaction: invalid curve  "UN"
----------- 0
panic: runtime: allocation size out of range

goroutine 1 [running]:
reflect.unsafe_NewArray(0x64daa0, 0xce6f4f3493e8ab, 0x64daa0)
	/usr/local/go/src/runtime/malloc.go:1222 +0x35
reflect.MakeSlice(0x7d38e0, 0x6128e0, 0xce6f4f3493e8ab, 0xce6f4f3493e8ab, 0x0, 0x100, 0x7ce840)
	/usr/local/go/src/reflect/value.go:2299 +0xd0
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0xc0000b4800, 0xc0001c0000, 0x0, 0x0, 0x0, 0x197, 0x6128e0)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:505 +0xbbf
github.com/eoscanada/eos-go.(*Decoder).decodeStruct(0xc00074a1b0, 0x62fdc0, 0xc0001c0000, 0x7d38e0, 0x648400, 0x648400, 0xc0001c0000, 0x199, 0x7ce840, 0xc000012280)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:568 +0x385
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0x62fdc0, 0xc0001c0000, 0x0, 0x0, 0x0, 0xc0004d8000, 0x199)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:514 +0xa25
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0x625e60, 0xc0004d8010, 0x0, 0x0, 0x0, 0x199, 0x639ee0)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:426 +0x2908
github.com/eoscanada/eos-go.(*Decoder).decodeStruct(0xc00074a1b0, 0x60c080, 0xc0004d8000, 0x7d38e0, 0x632c00, 0x632c00, 0xc0004d8000, 0x199, 0x7ce840, 0xc000012290)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:568 +0x385
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0x60c080, 0xc0004d8000, 0x0, 0x0, 0x0, 0x199, 0x199)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:514 +0xa25
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0xc0000b4740, 0xc0001621d0, 0x0, 0x0, 0x0, 0x197, 0x6126e0)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:507 +0xcef
github.com/eoscanada/eos-go.(*Decoder).decodeStruct(0xc00074a1b0, 0x60a9c0, 0xc0001a4010, 0x7d38e0, 0x63b860, 0x63b860, 0xc000162100, 0x199, 0x7ce840, 0xc000012290)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:568 +0x385
github.com/eoscanada/eos-go.(*Decoder).Decode(0xc00074a1b0, 0x60a9c0, 0xc0001a4010, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/zx/go/pkg/mod/github.com/eoscanada/eos-go@v0.9.1-0.20210115195118-6d94af7a8501/decoder.go:514 +0xa25
main.(*Reader).readSignedBlock(0xc000135f10, 0x5f58, 0x0, 0x5f58, 0x0, 0x0, 0x0)

**Comment by maoueh** [comment]
What version of nodeos produced this blocks.log file? Can you share it with us or a link somewhere? Are you able to tell on which block approximately it fails?

**Comment by maoueh** [comment]
There is probable a bug but without further info, impossible to work on it. Closing, if anyone can reproduce and provide a `blocks.log` to test, will be happy to take a look and I'll re-open.
