### ISSUE TITLE
Serialization of TimePointSec value is invalid.

### ISSUE THREAD

**Issue by keisuke-kanao** [eoscanada/eos-go#153]
`TimePointSec` is of type `uint32` so I think below line shold be modified such that it writes a `uint32` value.
https://github.com/eoscanada/eos-go/blob/develop/encoder.go#L173

**Comment by maoueh** [comment]
Yep your are right: https://github.com/EOSIO/fc/blob/ff56d25e587f8131cfde06f1eb61baa899bc8a89/include/fc/time.hpp#L121.

Feel free to propose a PR. Otherwise, we will fix this when we got some time in the upcoming weeks.

**Comment by maoueh** [comment]
Fixed by #154
