### ISSUE TITLE
Update README.md with endpoints

### ISSUE THREAD

**Issue by RedCuckoo** [eoscanada/eos-go#155]
File README.md have to be updated with the endpoints that work with this exact library and some problems have to be fixed (if needed I can file new issues for each of them).

Code snippet (with endpoint as program argument):
```
package main

import (
	"fmt"
	"github.com/eoscanada/eos-go"
	"os"
)

func main() {
	api := eos.New(os.Args[1])
	info, err := api.GetInfo()

	if err != nil{
		fmt.Println("Failed get info from api")
		fmt.Println(api)
		return
	}else{
		fmt.Println(info)
	}

	fromBlockNum := info.HeadBlockNum - 100

	toBlockNum := fromBlockNum + 100

	for fromBlockNum != toBlockNum{
		block, err := api.GetBlockByNum(fromBlockNum)

		fmt.Println(block.String())

		if err != nil{
			fmt.Println("Failed get block")
			return
		}

		transactionReceipts := block.Transactionshttps://api.jungle3.alohaeos.com

		for i, _ := range transactionReceipts {
			txID := transactionReceipts[i].Transaction.ID.String()
			fmt.Println(txID)

			transaction, err := api.GetTransaction(txID)
			if err == nil {
				fmt.Println(transaction)
			}else{https://api.jungle3.alohaeos.com
				fmt.Printf("failed to get transaction, err=%s\n", err)
			}
		}

		fromBlockNum++
	}
}
```
The provided mainnet endpoint in the README.md (___https://mainnet.eos.dfuse.io___) is not connecting with the following output:
```
Failed get info from api
&{0xc00009b140 https://mainnet.eos.dfuse.io <nil> false zlib map[] 0 0 <nil> {0 0 <nil>} {0 0} <nil>}
```
Community EOS testnet works correctly (___https://api.jungle3.alohaeos.com___)
The official one not (___https://api.testnet.eos.io___) with the output:
```
SignedBlock [70935901] with 0 txs
SignedBlock [70935902] with 1 txs
13594c378e68c05962a3d360d601166d3cd463f69c748012319db6ad2991410c
failed to get transaction, err=Not Found: unspecified: Unknown Endpoint
SignedBlock [70935903] with 0 txs
```

I think it will be good to provide support for different endpoints (though as it should work all the same, it might be some odd behaviour in this module). 
Or at least, it will be a good idea to provide the list of working endpoints to ease developer's lives. 

EDIT: forgot to mention a significant case, endpoint ___https://api.eosflare.io___. It's the working endpoint from the relative to the link website. The get transaction info fails with the following information:
```
SignedBlock [187989722] with 3 txs
fbe8fa825da688438909bace3a6264a2d0caa2d8d8ba9cd0547444e4dd04be95
failed to get transaction, err=Unmarshal: parsing time ""2021-06-08T12:08:27.000Z"" as ""2006-01-02T15:04:05"": cannot parse "Z"" as """
aeee29025e4fee268f0a2d2b513c1351a185e024aa58c91bbdc4d79ca40afa1c
failed to get transaction, err=Unmarshal: parsing time ""2021-06-08T12:08:27.000Z"" as ""2006-01-02T15:04:05"": cannot parse "Z"" as """
c345a9a332645950c22bb2a196472f332b1a5140798686acf981a01d72da17ab
failed to get transaction, err=Unmarshal: parsing time ""2021-06-08T12:08:28.000Z"" as ""2006-01-02T15:04:05"": cannot parse "Z"" as """
```
It is the problem in time parsing.

**Comment by maoueh** [comment]
The endpoints have been updated everywhere (in README and in examples). The time parsing problem, I think it's fixed as well, you can open a new issue if it's still a problem.
