### ISSUE TITLE
 How to change the public key prefix

### ISSUE THREAD

**Issue by kimtony** [eoscanada/eos-go#158]
hello, now i use this api.Signer.AvailableKeys()  of func to get a public key : "EOS8eLGFHoVAV31z6kM2m1T6o6mSFTmMgv3LoJBGcMxxM8Z4gxwPD"

but,i want get like this "PUB_K1_8eLGFHoVAV31z6kM2m1T6o6mSFTmMgv3LoJBGcMxxM8Z4gxwPD" or another no defalut Eos prefix.

i read the code "
const PublicKeyPrefix = "PUB_"
const PublicKeyK1Prefix = "PUB_K1_"
const PublicKeyR1Prefix = "PUB_R1_"
const PublicKeyWAPrefix = "PUB_WA_"
const PublicKeyPrefixCompat = "EOS"
"
not can be change.

What should I do？ Can any great god take a look for help?

**Comment by maoueh** [comment]
By default, if the key is PrefixCompat or K1, it is printed with the compat prefix. There is not possibility right now to actually choose which prefix between K1 or Compat to use. The code currently doesn't keep around what was the actual real prefixed used when parsed.

You could simply replace `EOS` by `PUB_K1_` manually after the transformation. For example with a `keyToString` function:

```
func keyToString(key ecc.PublicKey) (out string) {
	out = key.String()
	if key.Curve == ecc.CurveK1 && len(out) > len(ecc.PublicKeyPrefixCompat) {
		out = ecc.PublicKeyK1Prefix + out[len(ecc.PublicKeyPrefixCompat):]
	}

	return
}
```

If you use `develop` branch, the values are not `const` anymore and can be overridden. But not that overriding the  `PublicKeyPrefixCompat` directly will preventing parsing keys that has `EOS` as a prefix:

```
package main

import (
	"context"
	"fmt"

	"github.com/eoscanada/eos-go"
	"github.com/eoscanada/eos-go/ecc"
)

func init() {
	ecc.PublicKeyPrefixCompat = "PUB_K1_"
}

func main() {
	keyBag := eos.NewKeyBag()

	// Public key is EOS8AwiufQmVEquQhCML6nYxfXmwPkBm6e7UmTVWKbpVneZtsfwgk
	if err := keyBag.Add("5HqkuMAeJU1ThVB2PbjcjXbzuprrKCBNSwFMjVBygU4ocSpFAxd"); err != nil {
		panic(fmt.Errorf("add key: %w", err))
	}
	
	// This will panics below since `EOS` prefix is not known anymore
	//_, err := ecc.NewPublicKey("EOS8AwiufQmVEquQhCML6nYxfXmwPkBm6e7UmTVWKbpVneZtsfwgk")
	//if err != nil {
	//	panic(fmt.Errorf("unable to obtain keys: %w", err))
	//}

	keys, err := keyBag.AvailableKeys(context.Background())
	if err != nil {
		panic(fmt.Errorf("unable to obtain keys: %w", err))
	}

	for _, key := range keys {
		fmt.Printf("Key %s\n", key)
	}

	fmt.Println("Done")
}
```
