### ISSUE TITLE
use SignPushActions something err

### ISSUE THREAD

**Issue by kimtony** [eoscanada/eos-go#160]
hello,i use SignPushActions to call contract but it has something err 

**err:**

`err--- Internal Service Error: eosio_assert_message assertion failure: assertion failure with message: datastream attempted to read past the end`

**here my code :**

`
apiEos := eos.New(configs.EosAddr())
	key := "" 
	signer := eos.NewKeyBag()                           
	err := signer.ImportPrivateKey(context.Background(), key)
	apiEos.Debug = true
	if err != nil {
		global.Logger.Errorf("[PushSignAction] ImportPrivateKey failed. error: %v", err)
		return
	}
	apiEos.SetSigner(signer)

	action := &eos.Action{
		Account: eos.AN("test4"), 		
		Name:    eos.ActionName("getkey"),   
		Authorization: []eos.PermissionLevel{
			{
				Actor:      eos.AccountName("movienodeab"),
				Permission: eos.PermissionName("active"),
			},
		},
		ActionData: eos.NewActionData( NftActionData{
			Owner: "movienodeab",
			Tokid: "21",
		}),
	}
	resp, err := apiEos.SignPushActions(context.Background(), action)
	if err != nil {
		fmt.Println("---------报错：err---", err.Error())
		return
	}`

-------------------------------------

I tried it, it seems that NewActionData has no effect, but it can't be debugged.
What should I do？ Can any great god take a look for help?

**Comment by maoueh** [comment]
- Are you using the `develop` branch in your code, latest code is on `develop`? 
- `NftActionData` is your own type, ensure that it fits your contract definition, a mistmatch between the types and expected smart contract is likely here.

**Comment by kimtony** [comment]
> * Are you using the `develop` branch in your code, latest code is on `develop`?
> * `NftActionData` is your own type, ensure that it fits your contract definition, a mistmatch between the types and expected smart contract is likely here.

Hello, I am using v0.9.0 version，

this is the struct 
type NftActionData struct {
	Owner string `json:"owner"`
	Tokid string `json:"tokid"`
}

contract data is :
{
  "owner" : "account",
  "tokid" : "12"
}

The contract data types are the same, and it is a bit unchecked at present，and i use eos.js,it can work.

**Comment by kimtony** [comment]
If I use this to declare action data, it can run, but the data posted by calling push_transaction is not the parameter I submitted

eos.NewActionData(map[string]interface{}{
	"owner": "movienodeab",
	"tokid": "21",
})

**Comment by maoueh** [comment]
Your ABI is not matching your `NftData`. You used `string` for both types but I highly doubt it's the case. Your ABI defines the types to use. You cannot use `string` everywhere.

```
type NftActionData struct {
Owner eos.Name json:"owner"
Tokid eos.Name json:"tokid"
}
```

Seems like a more likely definition, check the ABI types. `name == eos.Name`, `string == string`, `uint64 == uint64`, etc.

**Comment by kimtony** [comment]
> Your ABI is not matching your `NftData`. You used `string` for both types but I highly doubt it's the case. Your ABI defines the types to use. You cannot use `string` everywhere.
> 
> ```
> type NftActionData struct {
> Owner eos.Name json:"owner"
> Tokid eos.Name json:"tokid"
> }
> ```
> 
> Seems like a more likely definition, check the ABI types. `name == eos.Name`, `string == string`, `uint64 == uint64`, etc.


Thank you very much. The Tokid type problem of NftActionData is solved.

**Comment by kimtony** [comment]
hello,i have another problem,i use this method it not response something,and i open the debug api , i want to it response like this img:
![image](https://user-images.githubusercontent.com/34413109/128964087-3ccb273f-ade8-4f3a-9664-464625341b02.png)

but this method is response like this img:
![image](https://user-images.githubusercontent.com/34413109/128964256-18b28759-d29c-4455-a80c-81579453fd13.png)

please,What should I do？
