### ISSUE TITLE
can i use SignPushActions method response debug api'data?

### ISSUE THREAD

**Issue by kimtony** [eoscanada/eos-go#161]
hello,i have another problem,i use this method it not response something,and i open the debug api , i want to it response like this img:
![image](https://user-images.githubusercontent.com/34413109/128964087-3ccb273f-ade8-4f3a-9664-464625341b02.png)

but this method is response like this img:
![image](https://user-images.githubusercontent.com/34413109/128964256-18b28759-d29c-4455-a80c-81579453fd13.png)

please,What should I do？

_Originally posted by @kimtony in https://github.com/eoscanada/eos-go/issues/160#issuecomment-896468747_

**Comment by maoueh** [comment]
Maybe you could write your solution so it might helps other in the future.
