### ISSUE TITLE
Why the newest master branch commits doesn't have the version tag? 

### ISSUE THREAD

**Issue by kirill-kostenetskyi** [eoscanada/eos-go#162]
Hi there!
I want to create a fork and add some necessary things for my project (add to the Trace model the `return_value_data` parameter) but I can't understand why the latest versions don't have a version tag. There are many changes up the master branch including breaking changes like context parameters since v0.9.0. Is there any reason for not tagging the newest commits? Just wondering which version I should fork and add my the changes

Thanks!

**Comment by maoueh** [comment]
Yeah we kind of went really a bit organic, sorry about that. You should base everything on `develop` branch, this is the most up to date version with all the recent changes (and indeed, some backward incompatible).

I'll leave it open until we merged stuff back in `master` and tag a release.

Note that even in the future, all development is done on the `develop` branch.

**Comment by kirill-kostenetskyi** [comment]
@maoueh thanks a lot!
