### ISSUE TITLE
get_actions return "Unknown Endpoint for account"

### ISSUE THREAD

**Issue by elricWu** [eoscanada/eos-go#164]
When I use GetActions, it always return  an error "Not Found: unspecified: Unknown Endpoint for account". 
I used https://jungle3.cryptolions.io:443 just for test. 
Is there anyone  help me ?

**Comment by maoueh** [comment]
Sorry for the late response, `GetActions` I think requires an history solution, so not every endpoint can work. If you have an endpoint that works from `curl` but does not in `eos-go`, please re-open with further details and I can take a look.
