### ISSUE TITLE
run demo code ，an error happend when download streamingfast  

### ISSUE THREAD

**Issue by yekai1003** [eoscanada/eos-go#167]
ubuntu@VM-16-4-ubuntu:~/gowork/src/eosdemo$ go mod init eosdemo
go: creating new go.mod: module eosdemo
go: to add module requirements and sums:
	go mod tidy
ubuntu@VM-16-4-ubuntu:~/gowork/src/eosdemo$ go mod tidy
go: finding module for package github.com/streamingfast/cli
go: finding module for package github.com/eoscanada/eos-go
go: downloading github.com/streamingfast/cli v0.0.2
go: downloading github.com/eoscanada/eos-go v0.10.0
go: found github.com/eoscanada/eos-go in github.com/eoscanada/eos-go v0.10.0
go: found github.com/streamingfast/cli in github.com/streamingfast/cli v0.0.2
go: eosdemo imports
	github.com/streamingfast/cli: github.com/streamingfast/cli@v0.0.2: parsing go.mod:
	module declares its path as: github.com/dfuse-io/cli
	        but was required as: github.com/streamingfast/cli

**Comment by maoueh** [comment]
This is now all fixed in `develop` and `master` branches.
