### ISSUE TITLE
Always get `resource not found` error

### ISSUE THREAD

**Issue by polyrabbit** [eoscanada/eos-go#17]
I'm playing with the go library, but it always returns `resource not found` error:

```go
package main

import (
	"fmt"
	"github.com/eoscanada/eos-go"
)

func main() {
	api := eos.New("http://mainnet.eoscalgary.io")
	resp, err := api.GetTransactions(eos.AccountName("gqytiobtgage"))
	if err != nil {
		fmt.Println("Err", err)
	} else {
		fmt.Println(resp)
	}
}

```

Am I using it the wrong way, or something wrong with the api? thanks!

**Comment by nanmu42** [comment]
`GetTransactions()` method calls RPC api `account_history::get_transactions`, which is deprecated.

An alternative choice is `history::get_actions`, not implemented by eos-go, yet.

Mind that `history::get_actions` is resource spending and needs some modification on RPC node, which makes it unlikely for a public node to have.

**Comment by polyrabbit** [comment]
Thanks for your info, the library works fine now, closing!
