### ISSUE TITLE
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: Cannot wear this item at the moment","file":"cf_system.cpp","line_number":14,"method":"eosio_assert"}]}}

### ISSUE THREAD

**Issue by lambogreny** [eoscanada/eos-go#171]
&eos.Action{
		Account: eos.AccountName("atomicassets"),
		Name:    eos.ActionName("transfer"),

		Authorization: []eos.PermissionLevel{
			{
				Actor:      eos.AccountName(account),
				Permission: "active",
			},
		},

		ActionData: eos.NewActionData(struct {
			From     eos.AccountName `json:"from"`
			To       eos.AccountName `json:"to"`
			AssetIds []eos.Asset     `json:"asset_ids"`
			Memo     string          `json:"memo"`
		}{
			AssetIds: []eos.Asset{eosAssetID},
			From:     eos.AccountName(account),
			Memo:     "burn",
			To:       eos.AccountName("farmersworld"),
		}),
	})

**Comment by maoueh** [comment]
The error message seems pretty clear about the problem: `Cannot wear this item at the moment`? This is sent by the smart contract when the action was executed.

Cannot you further improve your issue report, because it's not easy to help you.
