### ISSUE TITLE
How to implement custom actions ，How to get serializetransaction，（PVT_K1 ）Unable to verify, output public key does not match

### ISSUE THREAD

**Issue by zhitunAI** [eoscanada/eos-go#180]
actions [
   
    {
      "account": 'xxxx',
      "name": "xxx",
      "data": {
        "message":"06d9d67c4644367a"
        },
      "authorization": [
          {
            "actor": newwaxname,
            "permission": "active"
          }
      ]
    },
    {
      "account": "eosio",
      "authorization": [
        {
          "actor": eosname,
          "permission": "active"
        }
      ],
      "data": {
        "account": eosname,
        "bytes": 100
      },
   
      "name": "sellram"
    }
 ]

**Comment by maoueh** [comment]
Please split each issue independently.
