### ISSUE TITLE
How to get serializetransaction？eosjs： api.serializeTransaction(sTransaction)

### ISSUE THREAD

**Issue by zhitunAI** [eoscanada/eos-go#182]
serializedTransaction: Uint8Array(100) [
150, 47, 188, 98, 10, 106, 235, 182, 187, 130, 0, 0,
0, 0, 2, 0, 0, 232, 134, 131, 140, 41, 61, 0,
0, 0, 0, 0, 80, 41, 157, 1, 16, 102, 158, 154,
34, 100, 100, 204, 0, 0, 0, 0, 168, 237, 50, 50,
0, 0, 0, 0, 0, 0, 234, 48, 85, 0, 0, 0,
64, 154, 27, 163, 194, 1, 0, 164, 225, 0, 1, 14,
138, 75, 0, 0, 0, 0, 168, 237, 50, 50, 16, 0,
164, 225, 0, 1, 14, 138, 75, 100, 0, 0, 0, 0,
0, 0, 0, 0
],

eosjs：
api.serializeTransaction(sTransaction)

eos-go：???

**Comment by maoueh** [comment]
See https://github.com/eoscanada/eos-go/blob/develop/example_trx_pack_test.go

You can also lurk in https://github.com/eoscanada/eosc which makes heavy use of `eth-go` library and can make you learn how to do the different things you want to do.
