### ISSUE TITLE
How to implement custom actions?

### ISSUE THREAD

**Issue by zhitunAI** [eoscanada/eos-go#183]
let pay =[

	{
		"account": 'xxxx',
		"name": "xxx",
		"data": {
			"message": "06d9d67c4644367a"
		},
		"authorization": [{
			"actor": newwaxname,
			"permission": "active"
		}]
	}, {
		"account": "eosio",
		"authorization": [{
			"actor": eosname,
			"permission": "active"
		}],
		"data": {
			"account": eosname,
			"bytes": 100
		},

		"name": "sellram"
	}
]

eosjs
await api.serializeActions(actions)

**Comment by maoueh** [comment]
Simply create helper function and define your `ActionData` struct in Go with the correct types like  `eos.Asset`, `eos.AccountName`, etc, you are able to create any actions you would like and the internal `eos-go` encoder will know how to serialize it correctly.

See [NewTransfer](https://github.com/eoscanada/eos-go/blob/a2c2bb7c80a0f135f3b5caf88166a14db0a5e965/token/transfer.go#L5) for example and full package that define standard actions like [System Actions](https://github.com/eoscanada/eos-go/blob/e3c3192ee4f4b61f219c124d8079bcb086f9740a/system)
