### ISSUE TITLE
How to be a maintainer with merge permission

### ISSUE THREAD

**Issue by psy2848048** [eoscanada/eos-go#188]
Hi,

This is Bryan from DELIGHT LABS, one of validator company in Cosmos-based & ETH-based projects.
But this contact is not on behalf of the team but as personal.

Before knowing this project, I was in the way of building of mine https://github.com/psy2848048/go-antelope-sdk/tree/feat/chain-api
But after aware this project, it would be better to build & maintain from this project.
As it seems that some issues & PRs are in pending but you have not enough time to look into it, I want to be a maintainer of this project and ask for a merge permission.
You may check my profession of EOSIO and blockchain area from my Github profile, especially the repo above & deveos, alwayseran repos (EOSIO educational example purpose), and other blockchain project portfolio.

Many thanks,
Bryan

**Comment by abourget** [comment]
@maoueh what do you think? ;-)

Psy, can you finalize a few of the PRs, participate in there, we'll merge one or two, we'll see how you work, and then we grant permissions?

Also, perhaps post this GH issue in a few channels where people know you, and they can vouch for you? We know quite a few folks from that community, we should be able to make a quick decision.

Quite a few projects rely on this repo, and it's a core repo, you'll understand we need to trust but verify ;-)

**Comment by psy2848048** [comment]
I should've asked as like "For being a maintainer, which condition should I meet & which step would be needed" 😅 
If the question make you embarrassed, sorry for my impliteness and it should be more careful.

After a dApp builder (named LangChain) & EOSIO hackathon mentor/participant in 2018, I was away from EOSIO. So issue raisers could not know nor vouch me.
I met Yves and Damian from ENF (Damian is not employed but in the grant committee) a few weeks ago and talked about a contribution. And I thought that dedicately maintained Go SDK seems not yet exist and it could be a contribution point. But they found this repo and it had been maintained awesome by team-level work, though a little bit outdated recently.

Even I've never thought I can be granted immediately but want to know your procedure. And finalizing PR would be the best point to enter & practice the code.
In the middle of that, I have one question about "finalizing PR" - would it be a guide to the contributor, or a few direct commits from me?

**Comment by abourget** [comment]
Hmmm, we don't have a plan for PRs. If you see some dangling, take them one. If you see things evolving in the community where we aren't tracking as closely (I'm thinking new RPC endpoints that might have been added), you could update the lib to support them.
