### ISSUE TITLE
ecc.PublicKey  is not string

### ISSUE THREAD

**Issue by biancheng347** [eoscanada/eos-go#197]
{
    key: "string",
   weight:  1,
}

but, key is  ecc.PublicKey struct

**Comment by maoueh** [comment]
That is expected behavior, `key` should represents a valid ECC PublicKey, hence why it's `ecc.PublicKey`, use `key.String()` to get back the string representation.

**Comment by biancheng347** [comment]
The back-end
json:{
"key": "string"
}

The get_account method returns key: ""

If I get the ecc.pubkey object and I have no problem with key.string (), how can I now be compatible with back-end key:string

**Comment by biancheng347** [comment]
Also, how to get http body raw data method and why, mainly if the method model is not consistent with the backend json, we can parse it ourselves with body.

**Comment by maoueh** [comment]
Sorry, probably barrier of language, I don't understand your problem at all. Provide exact reproduction case so I can see what you mean.

If you want HTTP body raw, make the request yourself using `net/http` package offered by Golang.

**Comment by biancheng347** [comment]
I mean if key is a string, get_account is acceptable. Instead of key is the structure

**Comment by anthonyzzy** [comment]
哈喽哥们 @biancheng347，我是EOS Canada原成员。你可以说中文解释你的问题，我帮你跟 matt 翻译
