### ISSUE TITLE
/get_block does not get to the previous blocks

### ISSUE THREAD

**Issue by LXHLeaner** [eoscanada/eos-go#199]
problem:  /get_block does not get to the previous blocks
chain: Tleos
endpoint: https://telos.greymass.com
height: 254559195

**Comment by matthewdarwin** [comment]
Why do you think this is an eos-go issue?

**Comment by maoueh** [comment]
@LXHLeaner Do you have further information? What is the error you get? What is wrong? Closing until you provide more information and we can determine if it's a bug in `eos-go` or not.
