### ISSUE TITLE
Error in NewAction

### ISSUE THREAD

**Issue by cookedsteak** [eoscanada/eos-go#2]
Dawn3.0  localnet
I deployed  the contract "eosio.token" on chain and follow the official guide.
All goes well when I use command line tool
> cleos  push action eosio.token transfer '["usera", "userb", "1 EOS", "memo"]' -p usera

to transfer some EOS token. 
Then I tried the code:

```
func (e *eos.API)TransferToken(from, to, memo string, quantity int64) (string, error){
	a := &eos.Action{
		Account: eos.AccountName("eosio.token"),
		Name: eos.ActionName("transfer"),
		Authorization: []eos.PermissionLevel{
			{eos.AccountName(from), eos.PermissionName("active")},
		},
		Data: eos.NewActionData(NewTransaction{
				From: from,
				To: to,
				Quantity: strconv.FormatInt(quantity, 10) + ` EOS`,
				Memo: memo,
		}),
	}

	e.SetSigner(eos.NewWalletSigner(e, "default"))
	tx, err := e.SignPushActions(a)
	if err != nil {
		return "", err
	}
	return tx.TransactionID, nil
}
```
but it always returns the following error:

> status code=400, body={"code":400,"message":"Bad Request","error":{"code":3030000,"name":"transaction_exception","what":"transaction validation exception","details":[{"message":"condition: assertion failed: read","file":"wasm_interface.cpp","line_number":805,"method":"eosio_assert"},{"message":"","file":"apply_context.cpp","line_number":30,"method":"exec_one"},{"message":"","file":"chain_controller.cpp","line_number":1989,"method":"__apply_transaction"},{"message":"","file":"chain_controller.cpp","line_number":2024,"method":"_apply_transaction"},{"message":"","file":"chain_controller.cpp","line_number":2225,"method":"wrap_transaction_processing"},{"message":"","file":"chain_controller.cpp","line_number":353,"method":"_push_transaction"},{"message":"","file":"chain_controller.cpp","line_number":328,"method":"_push_transaction"}]}}

Did I miss something when I tried to make this transaction?

**Comment by abourget** [comment]
Why don,t you use the `token.NewTransfer()` Action ? It's designed to reflect the main `transfer` action on the `eosio.token` contract..

You can use it as such https://github.com/eoscanada/eos-bios/blob/master/bios.go#L66

Sample:

```go
	_, err := b.API.SignPushActions(token.NewTransfer(from, to, qty, ""))
	if err != nil {
		return fmt.Errorf("transfer: %s", err)
	}
```

Take a look here and here:
* https://github.com/eoscanada/eos-go/tree/master/system
* https://github.com/eoscanada/eos-go/tree/master/token

**Comment by abourget** [comment]
I'm not sure where you got `NewTransaction`, and also your `Quantity` field seems odd.. not sure how it will serialize. You want to use an `eos.Asset` object there.

**Comment by cookedsteak** [comment]
Solved, the main problem was the object type.
Thank you again @abourget.
