### ISSUE TITLE
abi  Decoding

### ISSUE THREAD

**Issue by mingtianquan** [eoscanada/eos-go#221]
The obtained abi is Base64, but using
func DecodeABI(base64ABI string) (eos.ABI, error) {
decoded, err := base64.StdEncoding.DecodeString(base64ABI)
if err !=  nil {
return eos.ABI{}, err
}

var abi eos.ABI
err = eos.UnmarshalBinary(decoded, &abi)
if err !=  nil {
return eos.ABI{}, err
}
return abi, nil
}
Decoding failed
DmVvc2lvOjphYmkvMS4yABMHYWNjb3VudAABB2JhbGFuY2UFYXNzZXQIYXBwcm92YWwAAgdzcGVuZGVyBG5hbWUHYmFsYW5jZQVhc3NldAdhcHByb3ZlAAQFb3duZXIEbmFtZQdzcGVuZGVyBG5hbWUIcXVhbnRpdHkFYXNzZXQEbWVtbwZzdHJpbmcFY2xvc2UAAgVvd25lcgRuYW1lBnN5bWJvbAZzeW1ib2wGY3JlYXRlAAIGaXNzdWVyBG5hbWUObWF4aW11bV9zdXBwbHkFYXNzZXQOY3VycmVuY3lfc3RhdHMAAwZzdXBwbHkFYXNzZXQKbWF4X3N1cHBseQVhc3NldAZpc3N1ZXIEbmFtZQxkZWx3aGl0ZWxpc3QAAghhY2NfbmFtZQRuYW1lCHRvX3Njb3BlBG5hbWUHZGVzdHJveQADBGZyb20EbmFtZQhxdWFudGl0eQVhc3NldARtZW1vBnN0cmluZwVpc3N1ZQADAnRvBG5hbWUIcXVhbnRpdHkFYXNzZXQEbWVtbwZzdHJpbmcMbG9ja2VkX3Rva2VuAAEHYmFsYW5jZQVhc3NldARvcGVuAAMFb3duZXIEbmFtZQZzeW1ib2wGc3ltYm9sCXJhbV9wYXllcgRuYW1lBnJldGlyZQACCHF1YW50aXR5BWFzc2V0BG1lbW8Gc3RyaW5nDHNldHdoaXRlbGlzdAACCGFjY19uYW1lBG5hbWUIdG9fc2NvcGUEbmFtZ QZ0cl9mZWUAAwJpZAZ1aW50NjQEcmF0ZQZ1aW50MTYGZmVlX3RvBG5hbWUIdHJhbnNmZXIABARmcm9tBG5hbWUCdG8EbmFtZQhxdWFudGl0eQVhc3NldARtZW1vBnN0cmluZwx0cmFuc2ZlcmZyb20ABQZ3b3JrZXIEbmFtZQRmcm9tBG5hbWUCdG8EbmFtZQhxdWFudGl0eQVhc3NldARtZW1vBnN0cmluZwl1bmFwcHJvdmUABAVvd25lcgRuYW1lB3NwZW5kZXIEbmFtZQhxdWFudGl0eQVhc3NldARtZW1vBnN0cmluZwt1cGRhdGV0cmZlZQACBHJhdGUGdWludDY0BmZlZV90bwRuYW1lCndoaXRlX2xpc3QAAQhhY2NfbmFtZQRuYW1lDQAAAEBtems1B2FwcHJvdmUAAAAAAACFaUQFY2xvc2UAAAAAAKhs1EUGY3JlYXRlAJCxiyq7xqNKDGRlbHdoaXRlbGlzdAAAAADA05uxSgdkZXN0cm95AAAAAAAApTF2BWlzc3VlAAAAAAAAMFWlBG9wZW4AAAAAAKjrsroGcmV0aXJlAJCxiyq7xrPCDHNldHdoaXRlbGlzdAAAAABXLTzNzQh0cmFuc2ZlcgAg6V1XLTzNzQx0cmFuc2ZlcmZyb20AAABQm95azdQJdW5hcHByb3ZlAACUWjerbFLVC3VwZGF0ZXRyZmVlAAYAAAA4T00RMgNpNjQAAAdhY2NvdW50AADA0W x6azUDaTY0AAAIYXBwcm92YWwApoI0JwURjQNpNjQAAAxsb2NrZWRfdG9rZW4AAAAAAJBNxgNpNjQAAA5jdXJyZW5jeV9zdGF0cwAAAAAApdbNA2k2NAAABnRyX2ZlZQAAyNhFlV3jA2k2NAAACndoaXRlX2xpc3QAAAAAAAA==

**Comment by mingtianquan** [comment]
How to make a transfer using this ABI

**Comment by mingtianquan** [comment]
package main

import (
	"context"
	"fmt"
	"github.com/eoscanada/eos-go"
	"github.com/eoscanada/eos-go/token"
	"io/ioutil"
	"log"
)

// 从文件读取 ABI 二进制内容
func LoadABIBinary(filePath string) ([]byte, error) {
	// 读取文件内容
	abiBinary, err := ioutil.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read ABI file: %v", err)
	}
	return abiBinary, nil
}

// 使用 ABI 转换并生成转账的 action
func CreateTokenTransferAction(abiBinary []byte, from, to eos.AccountName, quantity eos.Asset, memo string) (*eos.Action, error) {
	// 初始化 EOS API
	api := eos.New("https://cs.zhongchuangshuofeng.com") // 更换为您的 EOS 节点

	// 解码 ABI
	abi := eos.ABI{}
	err := eos.UnmarshalBinary(abiBinary, &abi)
	if err != nil {
		return nil, fmt.Errorf("failed to decode ABI: %v", err)
	}

	// 通过 ABI 创建转账 Action
	action := eos.Action{
		Account: eos.AccountName("zwt.token"), // token 合约名称
		Name:    eos.ActionName("transfer"),
		Authorization: []eos.PermissionLevel{
			{Actor: from, Permission: eos.PermissionName("active")},
		},
		ActionData: eos.NewActionData(token.Transfer{
			From:     from,
			To:       to,
			Quantity: quantity,
			Memo:     memo,
		}),
	}
	fmt.Println("[api].",api)
	// 通过 ABI 进行进一步解析或操作
	// 这里您可以使用 ABI 解析具体的 action 或方法

	return &action, nil
}

func main() {
	// 加载 ABI 文件
	abiBinary, err := LoadABIBinary("output.bin") // 这是您的二进制 ABI 文件路径
	if err != nil {
		log.Fatalf("Error loading ABI: %v", err)
	}

	// 创建 Token 转账的 Action
	from := eos.AccountName("m1bc2b1e31b1")
	to := eos.AccountName("m1e2335322cb")
	quantity := eos.Asset{Amount: eos.Int64(100), Symbol: eos.Symbol{Precision: 4, Symbol: "ZWT"}} // 100.00 ZWT
	memo := "Transfer ZWT to recipient"
	action, err := CreateTokenTransferAction(abiBinary, from, to, quantity, memo)
	if err != nil {
		log.Fatalf("Error creating action: %v", err)
	}

	// 推送和签名操作
	PushSignAction(action)
}

// 推送和签名操作
func PushSignAction(action *eos.Action) {
	if action == nil {
		fmt.Println("[PushSignAction] Action is nil.")
		return
	}

	// 创建一个新的 Context
	ctx := context.Background()

	// 设置 EOS API 和私钥
	api := eos.New("https://cs.zhongchuangshuofeng.com")
	keyBag := eos.NewKeyBag()
       //I have cleared the private key
	// 导入私钥
	err := keyBag.ImportPrivateKey(ctx, "") // 替换为您的私钥
	if err != nil {
		fmt.Printf("[PushSignAction] ImportPrivateKey failed. error: %v\n", err)
		return
	}
	api.SetSigner(keyBag)

	// 推送签名后的 Action
	resp, err := api.SignPushActions(ctx, action)
	if err != nil {
		fmt.Printf("[PushSignAction] Push action failed. error: %v\n", err)
		return
	}
	fmt.Printf("[PushSignAction] Action pushed successfully: %v\n", resp)
}



调试报错[PushSignAction] Push action failed. error: get_required_keys: Invalid Request: invalid http request: Unable to parse valid input from POST body

**Comment by maoueh** [comment]
For the base64, I thought it could be because it was URLSafe base64, not I've tried all 4 base64 encoders (standard, standard no padding, URL, URL no padding) and not succeed. I conclude the base64 was indeed invalid.

For making a transfer, see https://github.com/eoscanada/eos-go/blob/develop/example_api_transfer_eos_test.go.
