### ISSUE TITLE
P2P: panic on UnregisterHandler

### ISSUE THREAD

**Issue by vovapi** [eoscanada/eos-go#24]
When unregistering HandlerFunc I'm getting panic:
```
panic: runtime error: comparing uncomparable type p2p.HandlerFunc
```

**Comment by vovapi** [comment]
Simple way to reproduce add `UnregisterHandler` call after registering in `registerInitHandler`:
https://github.com/eoscanada/eos-go/blob/16135e604a9d490f37a9ed90c479aabb39c250c5/p2p/client.go#L219

**Comment by maoueh** [comment]
Seems the `UnregisterHandler` has been removed completely from the library. Closing this issue.

Feel free to open up a feature request issue if you feel we needed to keep this.
