### ISSUE TITLE
Get actions API not found.

### ISSUE THREAD

**Issue by devjyk05** [eoscanada/eos-go#25]
Hi eoscanada 

First, thank you for creating a library.

I have a question, does the library not support the get _ action API?
I'd like to retrieve the transfer details, but I can't find them.
Thank you.

**Comment by abourget** [comment]
The `/v1/history/get_actions` endpoint is enabled by a `history_api_plugin` being loaded on the node. You also need to `filter-on` those contracts/actions you're interested in keeping a reference of.  Mind you, it will load all of that into RAM (!).. you might want to use the newly merged MongoDB plugin to write to mongo those things, which you can then query from the database.

The lib doesn't yet implement the `GetActions` endpoint, no.. we'll be adding that very soon :) unless pitch in first!

**Comment by thbourlove** [comment]
@abourget are you working on this now? if not, i can do this.

**Comment by maoueh** [comment]
This has landed, see #28
