### ISSUE TITLE
Why TransactionHeader.RefBlockNum is uint16 ?

### ISSUE THREAD

**Issue by cyhhao** [eoscanada/eos-go#27]
Now, the EOS main network block number is more than 7300000+ . it's bigger than uint16 , when I set RefBlockNum it will overflow.

**Comment by abourget** [comment]
The ref_block_* elements are only chunks of the block id, so you can check it points to the right block but it's shorter.

The block num is only the last 16 bits of the block num, so yes it will overflow, but paired with the other ref block element, it points to the right block ID without much ambiguity. 

A block num alone wouldn't be precise enough when mini forks are happening.

**Comment by maoueh** [comment]
So, to recap, RefBlockNum is not the real Block Num, only a reference for easier comparison within blocks that are close to each other.

Not a bug.
