### ISSUE TITLE
parse block error

### ISSUE THREAD

**Issue by ququzone** [eoscanada/eos-go#33]
parse #7897873 block occur below error

----
panic: runtime error: slice bounds out of range
github.com/eoscanada/eos-go.(*Decoder).readUvarint(0xc421849ea8, 0x0, 0x4ba2b4, 0x84d900)

**Comment by maoueh** [comment]
Seems to be fixed in latest version. The block JSON is not quite right however, but this is a different issue (see #34).

Closing, feel free to re-open if you still face the issue with the latest code.
