### ISSUE TITLE
I get block data through the GetBlockByNum No Data

### ISSUE THREAD

**Issue by halowallet** [eoscanada/eos-go#34]
i get block Num 6342084 

return :
{"expiration":"2018-07-17T11:19:05","ref_block_num":50301,"ref_block_prefix":2432041012,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosdactokens","name":"transfer","authorization":[{"actor":"gy4dkmjzhege","permission":"active"}],"hex_data":"a0986aff49988867100261f9519b8867881300000000000004454f534441430000"}],"transaction_extensions":[],"signatures":["SIG_K1_KXsd17mt6qf8JAHvRiVLRH93tMoQrkC69qhoS2suG8N3YYF54LTVkSwnh4t4wscDJXPnSAdbJZpSfHjJjSurDmwGCAxvTs"],"context_free_data":[]} <nil>

sucesss : 
![image](https://user-images.githubusercontent.com/40428442/43837148-3635273e-9b4a-11e8-95f9-1ce779c1de9a.png)

I can get the complete data through eos-js

here's my code 
<pre><code>
out,err := eosApi.GetBlockByNum(6342084)
if err != nil {
  log.Println("get block err")
}
signedBlock := out.SignedBlock
	for txNum := range signedBlock.Transactions {
		tx := signedBlock.Transactions[txNum]
		if tx.Transaction.Packed != nil {
			unpacked, err := tx.Transaction.Packed.Unpack()
			if err != nil {
				log.Println(" unpack tractions error  ", err.Error())
			}

			for idx := range unpacked.Actions {
				action := unpacked.Actions[idx]

				if action.Data != nil {
					err := action.MapToRegisteredAction()
					if err != nil {
						log.Fatalf("processAction:ction.MapToRegisteredAction %v", err.Error(),idx)
						continue
					}

					switch op := action.Data.(type) {
					case *token.Transfer:
						log.Printf("Transfer  From : %s , To : %s ",op.From,op.To)	// 191
					}

				}else{
					log.Println("no action.data")
				}
			}
		}
	}
</pre></code>

**Comment by halowallet** [comment]
- [ ]

**Comment by maoueh** [comment]
@halowallet Seems to be a JSON marshalling. I will check how to fix the issue in the upcoming days.

**Comment by maoueh** [comment]
It seems all the info is available. I added a test that you can check here to see how to retrieve all the data you need: https://github.com/eoscanada/eos-go/blob/master/responses_test.go#L22-L96

Also, here an example using the API directly:

```
package main

import (
	"fmt"

	"github.com/eoscanada/eos-go"
)

type Transfer struct {
	From     eos.AccountName `json:"from"`
	To       eos.AccountName `json:"to"`
	Quantity eos.Asset       `json:"quantity"`
	Memo     string          `json:"memo"`
}

func main() {
	eos.RegisterAction(eos.AccountName("eosdactokens"), eos.ActionName("transfer"), Transfer{})

	api := eos.New("https://mainnet.eoscanada.com")
	resp, err := api.GetBlockByNum(6342084)
	if err != nil {
		fmt.Println("get block err")
	}

	transaction, err := resp.Transactions[0].Transaction.Packed.Unpack()
	if err != nil {
		fmt.Println("unpack transaction err")
	}

	transfer, ok := transaction.Transaction.Actions[0].Data.(*Transfer)
	if !ok {
		fmt.Println("expecting transaction transfer data")
	}

	fmt.Printf("From: %s\n", transfer.From)
	fmt.Printf("To: %s\n", transfer.To)
	fmt.Printf("Quantity: %s\n", transfer.Quantity)
	fmt.Printf("Memo: %s\n", transfer.Memo)
}
```

Don't hesitate to continue the conversation if you need further assistance.
