### ISSUE TITLE
How to set owner permission by updateauth ?

### ISSUE THREAD

**Issue by cookedsteak** [eoscanada/eos-go#38]
How I use NewUpdateAuth:
```
system.NewUpdateAuth(
		eos.AN("account1"),
		eos.PN("active"),
		eos.PN("owner"),
		eos.Authority...,
		eos.PN("active"),
	)
```
It's ok when I set active permission. I filled key 'parent' with the value 'owner'.
Then I wanna set owner permission, and I left a blank to key 'parent', but seem no use.
some problems occurs:
```
1953216ms thread-0 http_plugin.cpp:406 handle_exception ] Exception Details: 3050000 action_validate_exception: action exception
Cannot set an authority as its own parent
{}
thread-0 eosio_contract.cpp:214 apply_eosio_updateauth
```
So I think the main problem may be the extra key 'parent' shouldn’t be packed when setting
the owner permission.  [Reference issue](https://github.com/EOSIO/eos/issues/4686)

**Comment by cookedsteak** [comment]
Solved, just keep blank for parent, and use owner permission for usingPermission.

**Comment by Quartzant** [comment]
hello,   can you tell me how to set it to account?  I get a json by NewUpdateAuth  like this 
`{
    "account": "account2",
    "permission": "coder",
    "parent": "owner",
    "auth": {
        "threshold": 1,
        "keys": [
            {
                "key": "EOS6XjSzZFU7wvcPvPCW3rgPmWrgswK6rRDmYu99jATs9kHSiuHdD",
                "weight": 1
            }
        ]
    }
}`
but i dont know how to set it to my account.

**Comment by Quartzant** [comment]
> hello, can you tell me how to set it to account? I get a json by NewUpdateAuth like this
> `{ "account": "account2", "permission": "coder", "parent": "owner", "auth": { "threshold": 1, "keys": [ { "key": "EOS6XjSzZFU7wvcPvPCW3rgPmWrgswK6rRDmYu99jATs9kHSiuHdD", "weight": 1 } ] } }`
> but i dont know how to set it to my account.

I got it, It must push transations for  the data
