### ISSUE TITLE
Does not support DeleteAuth

### ISSUE THREAD

**Issue by vjoke** [eoscanada/eos-go#4]
Hi, guys, will this feature be added in the near future?

**Comment by abourget** [comment]
woah! crazy we didn't put that in yet.. I guess we weren't super systematic and we added what we needed as went..

@billettc .. this is one thing we'll want added, and to `eosc` too..

**Comment by vovapi** [comment]
It seems to be [implemented](https://github.com/eoscanada/eos-go/blob/master/system/deleteauth.go)...

And registered...
https://github.com/eoscanada/eos-go/blob/16135e604a9d490f37a9ed90c479aabb39c250c5/system/init.go#L24

@vjoke have you tried to import `system` sub-package?

What's the issue?

**Comment by vovapi** [comment]
Seems to be solved
@vjoke is it?

**Comment by maoueh** [comment]
`DeleteAuth` action has been added to library. Closing. Feel free to re-open if you feel this is not fixed correctly.
