### ISSUE TITLE
How can I create a new account by  api ?

### ISSUE THREAD

**Issue by riddlerx** [eoscanada/eos-go#46]
I am trying use the function  to create a new account ,  like this : 
NewCustomNewAccount
NewBuyRAM
NewDelegateBW
SignPushActions(newAaccountAction, buyRamAction, delegateAction)
but failed ,  How can I do it ?

**Comment by maoueh** [comment]
Can you provide the exact error message you get as well as the code you used to make it work. Please provide also the "debug" traces. To do so, use `api.Debug = true` right after having initialized the api object, should look something like this:

```
package main

import (
	"fmt"

	"github.com/eoscanada/eos-go"
)

func main() {
	api := eos.New("https://mainnet.eoscanada.com")
	api.Debug = true // <-- Add this line

	resp, err := api.GetInfo()
	if err != nil {
		fmt.Printf("Error occurred: %s", err)
		return
	}

	fmt.Printf("Response: %v", resp)
}
```

We need much more information to be able to help you on such "not working" problem

**Comment by riddlerx** [comment]
It seems working now .  I think the ram is not enough early I use.  but How can I config the ram value and delegateBW value with minimum ? 

actionResp, err := wallet_api.SignPushActions(
		system.NewCustomNewAccount("shangjing111", "shangjing122", a, b),
		system.NewBuyRAM(
			eos.AccountName("shangjing111"),
			eos.AccountName("shangjing122"),
			5000,
		),
		system.NewDelegateBW(
			eos.AccountName("shangjing111"),
			eos.AccountName("shangjing122"),
			eos.NewEOSAsset(1),
			eos.NewEOSAsset(1),
			true,
		),
	)

**Comment by maoueh** [comment]
You can check how it's implemented in `eosc`: https://github.com/eoscanada/eosc/blob/master/eosc/cmd/systemNewaccount.go

Closing as I think all the answers you seek are in the linked code above. Feel free to continue the discussion if needed.
