### ISSUE TITLE
GetActions post omitempty bug

### ISSUE THREAD

**Issue by newro** [eoscanada/eos-go#48]
Hi~ EOSCanada's eos-go made development much easier. Thank you.

If the Pos value of GetActionsRequest is set to 0 in the #41 issue added recently, the Pos field will be missing on the actual JSON request by the omitempty option.
This will prevent normal requests from being made.
Should not you change the int64 value of Pos to *int64?

**Comment by maoueh** [comment]
I removed the `omitempty` clauses for now as going with the pointer would have added "more" work on the calling site as pointer literal seems not easy in Go. 

Will look with the team for other better solution before re-introducing the `omitempty` clauses.
