### ISSUE TITLE
Signature is different

### ISSUE THREAD

**Issue by cuizx** [eoscanada/eos-go#49]
I generate a simple transaction through the command cleos with -d -j  options. Then I used eos.NewSignedTransaction() with the parameters in the json string(generated by cleos) . However the two signatures are different. 
Have you tested this?
If I am wrong, would you please give an example?

**Comment by maoueh** [comment]
Not impossible the signature do not match, I will need to take a look. Are you able to provide me with the exact steps and data so that I can reproduce that?
 
There is a PR pending that might fix this #36, I will check when I get some time.

**Comment by cuizx** [comment]
Environment: Jungle Test Net 
EOS version: 1.2.1
OS: Unbuntu Server 16.04

step 1: cleos transfer name1 name2 "10.0000 EOS" "test"  -d -j   //change the name to your own 
{
  "expiration": "2018-09-06T05:19:38",
  "ref_block_num": 16295,
  "ref_block_prefix": 778607569,
  "max_net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [{
      "account": "eosio.token",
      "name": "transfer",
      "authorization": [{
          "actor": "name1",
          "permission": "active"
        }
      ],
      "data": "0000d5cc4....................."               
    }
  ],
  "transaction_extensions": [],
  "signatures": [
    "SIG_K1_SIGNATURE SIGNED BY CLEOS WALLET"
  ],
  "context_free_data": []
}

step 2 eos-go: the main code as the following:

package main

import (
	"encoding/hex"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"
	"time"

	"github.com/eoscanada/eos-go"
	"github.com/eoscanada/eos-go/ecc"
)

func main(){
	action := &eos.Action{}

	pls := make([]eos.PermissionLevel, 0)
	pl := eos.PermissionLevel{}
	pl.Actor = "name1"
	pl.Permission = "active"
	pls = append(pls, pl)
	
	action.Account = "eosio.token	"
	action.Name = "transfer"
	action.Authorization = pls
	
	action.HexData, _ = hex.DecodeString("0000d5cc4.....................")
	actions := make([]*eos.Action, 0)
	actions = append(actions, action)
	
	tx := &eos.Transaction{}

	tx.ContextFreeActions = make([]*eos.Action, 0)
	tx.Actions = actions
	tx.RefBlockNum = 16295
	tx.RefBlockPrefix = 778607569
	t, _ := time.Parse("2006-01-02T15:04:05", "2018-09-06T05:19:38")
	tx.Expiration = eos.JSONTime{t}
	tx.Extensions = make([]*eos.Extension, 0)

	stx := eos.NewSignedTransaction(tx)

	privKey, _ := ecc.NewPrivateKey("the Private key of  name1")
	txdata, cfd, _ := stx.PackedTransactionAndCFD()
	chainID, _ := hex.DecodeString("038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca")
	sigDigest := eos.SigDigest(chainID, txdata, cfd)
	
	sig, _ := privKey.Sign(sigDigest)
	stx.Signatures = append(stx.Signatures, sig)
	fmt.Println(stx.String())
}

The two signatures are different.

I tried several other ways to generate transaction, e.g. 
        txopts := &eos.TxOptions{}
	txopts.ChainID, _ = 
        hex.DecodeString("038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca")
	txopts.HeadBlockID, _ = hex.DecodeString("0000.....")
	txopts.MaxCPUUsageMS = 0
	txopts.MaxNetUsageWords = 0
	txopts.DelaySecs = 0
	txopts.Compress = eos.CompressionNone

The result is the same above.

**Comment by abourget** [comment]
See #36 .. nothing guarantees a signature of a privkey+payload to be _identical_ each time, for it to be valid.  It will be canonical (thus recognized as valid by nodeos), but again that doesn't mean the serialization is the same.

See the linked issue for more details.
