### ISSUE TITLE
Rename SHA256Bytes to SHA256Hash

### ISSUE THREAD

**Issue by maoueh** [eoscanada/eos-go#58]
This would be a heavy refactor (still most probably a simple search/replace) for all consumers of the library out there.

Should probably go in a major iteration IMO.

**Comment by abourget** [comment]
There's a Go feature to do that easily:

https://golang.org/doc/go1.9#language

I think we should do those things sooner than later.

We haven't guaranteed non-breaking changes to `eos-go` yet..

**Comment by abourget** [comment]
What about `Checksum256` ? That's what nodeos uses, and we don't *really* know what it's the checksum of, and often it is *not* a SHA256.. like a `block_id` is a mixture of hash and block_num...

**Comment by maoueh** [comment]
Yeah, I agree, `Checksum256` seems like a good name.

**Comment by abourget** [comment]
Done. With type alias.
