### ISSUE TITLE
ABI Encoder/Decoder (1.1): Supports ABI variants

### ISSUE THREAD

**Issue by maoueh** [eoscanada/eos-go#59]
The ABI version 1.1. will contains a new feature to support variants in a type: a kind of container value that can hold N different types (one at a time though).

Implementation in: https://github.com/EOSIO/eos/pull/5652
Original issue: https://github.com/EOSIO/eos/issues/5599

**Comment by maoueh** [comment]
Linked issue: https://github.com/EOSIO/eos/pull/5680

**Comment by abourget** [comment]
Oh noo.. not cool :-) we'll do what with that? interface{} ? A strict with the different types in order or with `eos:"variant=0"` ?

**Comment by abourget** [comment]
We should go through the ABIs see if that's used.

**Comment by jafri** [comment]
Would love this to get implemented. 

In ABIs, it takes the structure

```
    "variants": [
        { "name": "result", "types": ["get_status_result_v0", "get_blocks_result_v0"] }
    ]
```

`get_status_result_v0` is a struct
