### ISSUE TITLE
how to do signer?

### ISSUE THREAD

**Issue by yekai1003** [eoscanada/eos-go#6]
err:no signer configured!

**Comment by thbourlove** [comment]
try to use a local key bag like below:
```
bag := eos.NewKeyBag()
bag.Add("your private key")
api.SetSigner(bag)
```

**Comment by abourget** [comment]
and there's also the `eos.NewWalletSigner()` which will use an `API` instance, and do signing through a standard `keosd` wallet (or our own `eosc vault` at github.com/eoscanada/eosc).

Does that help ?
