### ISSUE TITLE
Support ABI encoder version 1.1

### ISSUE THREAD

**Issue by maoueh** [eoscanada/eos-go#61]
This is a meta issue to track progress of ABI Encoder/Decoder to support ABI version 1.1.

 * [x] ABI Encoder/Decoder (1.1): Supports ABI variants (#59)
 * [x] ABI Encoder/Decoder (1.1): Supports binary extension (#60)

**Comment by abourget** [comment]
Missing will be encoding/decoding to/from bin <-> Go structs for variants.

Proposed addition:

```golang


type MaStruct struct {
	Memo string
	Key  VariantNameUint32
}

type VariantNameUint32 struct {
	EOS_Variant int

	Uint32Val uint32
	Name      Name
}

func (v *VariantNameUint32) SetUint32(bob uint32) {
	v.EOS_Variant = 0
	v.Uint32Val = bob
}

func (v *VariantNameUint32) SetName(bob eos.Name) {
	v.EOS_Variant = 1
	v.Name = bob
}
```

or something similar. Feedback welcome.

**Comment by maoueh** [comment]
Started initial approach in the library the supports binary + JSON format, see https://github.com/eoscanada/eos-go/blob/master/types.go#L1087. 

Usage example: [BlockSigningAuthority](https://github.com/eoscanada/eos-go/blob/master/p2ptypes.go#L316)
