### ISSUE TITLE
Extracting public key from the signature

### ISSUE THREAD

**Issue by hangaretto** [eoscanada/eos-go#67]
func TestSignaturePublicKeyExtraction in ecc/signature_test.go, replaced to  FixmeTestSignaturePublicKeyExtraction. Extracting public key from the signature now is not working?

**Comment by abourget** [comment]
No, it works in general.. just the case under test wasn't matching. We were checking that recently, but otherwise everything is fine.. the lib recovers and signs millions of transactions per day without a hitch.

**Comment by hangaretto** [comment]
Sorry, it works correctly.

```
chainID := []byte{207, 5, 123, 191, 183, 38, 64, 71, 31, 217, 16, 188, 182, 118, 57, 194, 45, 249, 249, 36, 112, 147, 108, 221, 193, 173, 224, 226, 242, 231, 220, 79}
payload := []byte{17, 219, 182, 91, 192, 68, 166, 40, 66, 32, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 234, 48, 85, 0, 17, 141, 167, 97, 211, 184, 154, 1, 0, 0, 0, 0, 0, 208, 85, 52, 0, 0, 0, 0, 168, 237, 50, 50, 24, 0, 0, 0, 0, 0, 208, 85, 52, 0, 0, 0, 181, 26, 208, 85, 52, 0, 0, 0, 0, 0, 208, 85, 52, 0}
```
passed the byte sequence directly
