### ISSUE TITLE
If transaction is packed with CompressionZlib, how to get right transaction id before push ?

### ISSUE THREAD

**Issue by suyhuai** [eoscanada/eos-go#71]
I got txid by **packedTx.ID().String()** before push action, 
but it is always different from the txid from 
PushTransaction response (**PushTransactionFullResp.transactionId**).

same to  receipt.Transaction.ID.String()
```
tid1 := packedTx.ID().String()
```
```
tid2 := receipt.Transaction.ID.String()
```
```
resp, err := n.c.PushTransaction(packed)
if err != nil {
	log.Error("send transaction fail, error: %s", err.Error())
}
tid3 :=  resp.TransactionID
```
```

tid1 == tid2 // true
tid1 == tid3 // false
```
but only tid3 can be searched on the blockchain explorer
please tell me how to get the tid3 before push tx. 
thank you
#74

**Comment by suyhuai** [comment]
I closed this issue, and created a pull request here: https://github.com/eoscanada/eos-go/pull/74
thx!

**Comment by billettc** [comment]
Fix by https://github.com/eoscanada/eos-go/pull/94
