### ISSUE TITLE
Do you have an options for writing eos smart-contracts?

### ISSUE THREAD

**Issue by SavostinVladimir** [eoscanada/eos-go#73]

**Comment by maoueh** [comment]
@SavostinVladimir Can you provide more details about what you are envisioning/need? The `eosc` binary can be used to create a "test" framework for smart contract. By coupling it with [eos-bios](https://github.com/eoscanada/eos-bios), it's possible to even create fully automated tests.

See https://github.com/eoscanada/eosio.forum for more details. Specially the [Development Section](https://github.com/eoscanada/eosio.forum#development) and the related script files ([run.sh](https://github.com/eoscanada/eosio.forum/blob/master/run.sh), [build.sh](https://github.com/eoscanada/eosio.forum/blob/master/build.sh) and [tests.sh](https://github.com/eoscanada/eosio.forum/blob/master/tests.sh)).

The "testing" framework lies in [tests/library.sh](https://github.com/eoscanada/eosio.forum/blob/master/tests/library.sh) and you can see its usage in the various test script in [tests folder](https://github.com/eoscanada/eosio.forum/blob/master/tests) (check out [post_validates_correct.sh](https://github.com/eoscanada/eosio.forum/blob/master/tests/post_validates_correctly.sh)  for an example).

We are planning to streamline all this in `eosc` directly, but it's not the main focus right now.

Closing the issue for now, feel free to continue the discussion with me for further details/help however.
