### ISSUE TITLE
Why struct TransactionWithID' ID is uint8?

### ISSUE THREAD

**Issue by zhaoxingjie** [eoscanada/eos-go#8]
in p2p_types.go, there is a struct of TransactionWithID:
    type TransactionWithID struct {
    	    ID     uint8 //
	    Packed PackedTransaction
    }
because ID's format like "00160d6f62968d7e04eab28658c854b7f838249499115a6504dcbc1a42da9f3a"  is what I got by get_blockinfo api, I am wondering why type of ID is uint8?
can someone explain?  thanks.

**Comment by abourget** [comment]
The C++ code has some, let's say, very interesting ways to do JSON serialization.. It has some `variants` types.. which can serialize in different ways in different situations.. it makes it very "interesting" to read.. and the `TransactionWithID` has a few cases handled..

We recently fixed the issue where the transaction was a simple string like you put... should work now..
In some situations, it is serialized as `[uint8, {transaction object}]`, where in the C++ code, the uint8 seems to denote the "type" of object you'll find as the `{transaction object}`.. TransactionWithID attempts to normalize all this funkyness, and gives you a single object to work with.

Mind you, it's not fully symmetric (as in: if you serialize your Go struct back to JSON, it won't necessarily look *exactly* was you read it at first), but hopefully it makes sense and helps.

Thanks for reaching out.. open more like these, others might find it useful too!
