### ISSUE TITLE
How to make a Action with empty data

### ISSUE THREAD

**Issue by wzxgww** [eoscanada/eos-go#91]
"actions": [
                {
                    "account": "testaction",
                    "name": "tick",
                    "authorization": [
                        {
                            "actor": "testaccount",
                            "permission": "active"
                        }
                    ],
                    "data": ""
                }
            ],
how to make a action like this, with empty data.

**Comment by billettc** [comment]
This code create an action ...
```
	action := &eos.Action{
		Account: eos.AccountName("testaction"),
		Name:    eos.ActionName("tick"),
		Authorization: []eos.PermissionLevel{
			{Actor: eos.AccountName("testaccount"), Permission: eos.PermissionName("active")},
		},
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.Encode(action)
```
... that will produce this json

```
{
  "account": "testaction",
  "name": "tick",
  "authorization": [
    {
      "actor": "testaccount",
      "permission": "active"
    }
  ]
}
```

**Comment by billettc** [comment]
This action will produce exactly the json you ask for
```
	action := &eos.Action{
		Account: eos.AccountName("testaction"),
		Name:    eos.ActionName("tick"),
		Authorization: []eos.PermissionLevel{
			{Actor: eos.AccountName("testaccount"), Permission: eos.PermissionName("active")},
		},
		ActionData: eos.ActionData{
			Data: "",
		},
	}
```
