### ISSUE TITLE
The error message is too small

### ISSUE THREAD

**Issue by free-snail** [eoscanada/eos-go#98]
I use cleos get the error is
`Error3060003: Contract Table Query Exception
Most likely, the given table doesn't exist in the blockchain.
Error Details:
key type required for non-primary index` 

but use eos-go only get 
`Internal Service Error`

**Comment by liyun2060** [comment]
I know  because u have a bug
at api.go line 587
code is 
`if err := json.Unmarshal(cnt.Bytes(), &apiErr); err != nil {`

the right code is

`if err := json.Unmarshal(cnt.Bytes(), &apiErr); err == nil {`

**Comment by billettc** [comment]
Thanks will look at it right away

**Comment by billettc** [comment]
Fix with
https://github.com/eoscanada/eos-go/commit/531fce78d2f51d288739d4da69dea6cb17000a01

**Comment by liyun2060** [comment]
Thank you

**Comment by billettc** [comment]
Fix by: https://github.com/eoscanada/eos-go/pull/99
